### ISSUE TITLE
Error parsing dates from NextSeq 2000

### ISSUE THREAD

**Issue by matthdsm** [MultiQC/MultiQC_SAV#2]
Plugin version: 0.0.2
MQC version:  v1.10.1

```
[ERROR  ]         multiqc : Oops! The 'SAV' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /projects/demultiplex/220112_VH00559_4_AAANY2JM5/RunParameters.xml
============================================================
Module SAV raised an exception: Traceback (most recent call last):
  File "/software/bcbio/anaconda/lib/python3.6/site-packages/multiqc_sav/modules/sav.py", line 294, in set_run_info
    parsed_run_date = datetime.strftime(datetime.strptime(run_date, "%y%m%d"), "%d-%m-%Y")
  File "/software/bcbio/anaconda/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/software/bcbio/anaconda/lib/python3.6/_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: -01-12T13:49:36Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/bcbio/anaconda/lib/python3.6/site-packages/multiqc/multiqc.py", line 594, in run
    output = mod()
  File "/software/bcbio/anaconda/lib/python3.6/site-packages/multiqc_sav/modules/sav.py", line 269, in __init__
    self.set_run_info(run_info_xml)
  File "/software/bcbio/anaconda/lib/python3.6/site-packages/multiqc_sav/modules/sav.py", line 296, in set_run_info
    parsed_run_date = datetime.strftime(datetime.strptime(run_date, "%m/%d/%Y %I:%M:%S %p"), "%d-%m-%Y")
  File "/software/bcbio/anaconda/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/software/bcbio/anaconda/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2022-01-12T13:49:36Z' does not match format '%m/%d/%Y %I:%M:%S %p'
```

**Comment by matthdsm** [comment]
fixed in 7be4695e583a6c62900ef44f20d79c65f1c7b1f4
